"""inclusao de campo

Revision ID: 265eef646654
Revises: 896174469b96
Create Date: 2024-04-09 11:03:16.662177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265eef646654'
down_revision = '896174469b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
